id: IC37DA7D4
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:45:09.187316
last_modified: 2023-02-09 14:45:09.187437
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: en
bases:
  0BDE:
    base_file: 0BDE.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
